#===============================================================================
#
#  $RCSfile$
#  Platform(s): C++, redhat 7.3, fedora
#               (redhat 8.0, redhat 9.0, macosx not tested)
#
#  Copyright (c) 2004 Framestore-CFC
#  All rights reserved.
#
#  This file contains Confidential and Proprietary source code, belonging to
#  Framestore-CFC its contents may not be disclosed to third parties, copied or
#  duplicated in any form, in whole or in part, without prior permission.
#
#  $Source$
#  $Revision$
#  $Date$
#  $Author$
#
#  Summary: This is a template Makefile for Maya
#
#  Description:
#
#===============================================================================
include ./liquidmayaVariables.mk
include /net/soft/fscfc/makefiles/generic.mk

#
# modify .o.so and .mel file name
#
VPATH       :=  bin/redhat/$(MAYAVER)/release/$(LIQRMAN)
PLUGINSO    :=  liquid.so
OBJECTS     :=
MELSCRIPTS  := ./mel/AEdagNodeInclude.mel ./mel/AEdependNodeTemplate.mel ./mel/AEliquidFGGIOverrideFlags.mel ./mel/AEliquidInstanceFlags.mel ./mel/AEliquidNurbsCurveShape.mel ./mel/AEliquidCamera.mel\
							 ./mel/AEliquidSetFlags.mel ./mel/AEliquidSubdivisionSurfaceShape.mel ./mel/AEobjectSetTemplate.mel ./mel/AEoldBlindDataBaseTemplate.mel ./mel/getMultiListerSelection.mel \
							 ./mel/liquidAttachParams.mel ./mel/liquidAttributes.mel ./mel/liquidAttrWindow.mel ./mel/liquidCommon.mel ./mel/liquidConvertMtor.mel ./mel/liquidConvMTOR.mel \
							 ./mel/liquidDelayedReadArchive.mel ./mel/liquidFileBrowser.mel ./mel/liquidFluid.mel ./mel/liquidFluidOutliner.mel ./mel/liquidGlobals.mel ./mel/liquidHelpers.mel \
							 ./mel/liquidIni.mel ./mel/liquidMenuHelp.mel ./mel/liquidParamDialogWindow.mel ./mel/liquidParseSlShader.mel ./mel/liquidPrefAttribute.mel ./mel/liquidReadArchive.mel \
							 ./mel/liquidReAttachParams.mel ./mel/liquidRenderCurve.mel ./mel/liquidRibBox.mel ./mel/liquidRibGen.mel ./mel/liquidShaders.mel ./mel/liquidShutdown.mel \
							 ./mel/liquidSlInfo.mel ./mel/liquidSLManager.mel ./mel/liquidSlParseSdl.mel ./mel/liquidSlParseSdr.mel ./mel/liquidSlParseSlo.mel ./mel/liquidSlParseSlx.mel ./mel/liquidSlParseSlb.mel \
							 ./mel/liquidStartup.mel ./mel/liquidSubdivInspector.mel ./mel/liquidSubdiv.mel ./mel/liquidSlParseLif.mel ./mel/liquidConvertShadingNetworkToRSL.mel \
							 ./mel/liquidWriteRSL_materials.mel ./mel/liquidWriteRSL_textures.mel ./mel/liquidWriteRSL_utilities.mel \
							 ./mel/liquidContainers.mel ./mel/liquidShaderNodes.mel \
							 ./mel/AEliquidSurfaceTemplate.mel ./mel/AEliquidDisplacementTemplate.mel ./mel/AEliquidVolumeTemplate.mel ./mel/AEliquidLightTemplate.mel ./mel/AEliquidRibBoxTemplate.mel \
							 ./mel/liquidBuildHypergraphNodePopupMenuItems.mel \
							 ./mel/registerLiquidRenderer.mel ./mel/AEliquidCoordSysTemplate.mel ./mel/liquidCreateGlobalsTab.mel ./mel/liquidRenderView.mel ./mel/createLiquidGlobalsTab.mel
ICONS       := ./icons/lif_cs.xpm ./icons/lif_shd.xpm ./icons/lif_tex.xpm \
							 ./icons/liquidInfo0.xpm ./icons/liquidInfo.xpm \
							 ./icons/liquidFluidEditDisplacementShader.xpm ./icons/liquidFluidEditLightShader.xpm ./icons/liquidFluidEditSurfaceShader.xpm \
							 ./icons/liquidFluid.xpm ./icons/liquidGlobalsWindow.xpm ./icons/liquidRender.xpm ./icons/liquidViewLastRib.xpm \
							 ./icons/light.jpg ./icons/noPreview.iff ./icons/liquidRibBoxSwatch.iff ./icons/liquidLightSwatch.iff \
							 ./icons/render_liquidDisplacement.xpm  ./icons/render_liquidLight.xpm  ./icons/render_liquidSurface.xpm  ./icons/render_liquidVolume.xpm ./icons/render_liquidRibBox.xpm \
							 ./icons/liquidMenuButton.xpm ./icons/liquidIcon2.xpm
SHADERS_SRC := ./shaders/src/liquidchecker.sl ./shaders/src/liquiddistant.sl ./shaders/src/liquidpoint.sl ./shaders/src/liquidspot.sl
SHADERS     := ./shaders/liquidchecker.slo ./shaders/liquiddistant.slo ./shaders/liquidpoint.slo ./shaders/liquidspot.slo
RENDERERS   := ./renderers/3Delight.lg ./renderers/Aqsis.lg ./renderers/PRMan.lg ./renderers/PRMan_12_5.lg  ./renderers/Pixie.lg

#all:debug

#release: CXXFLAGS += -O3
#release: $(PLUGINSO)

#debug: CXXFLAGS += -g
#debug: $(PLUGINSO)


#
# describe here how to compile $(PLUGINSO)
#
# modify pluginFileName.so
#
#$(PLUGINSO): $(OBJECTS)
#	-rm -f $@
#	$(LD) $(LDFLAGS) -o $@   $^ $(LDLIBS)

#$(PLUGINSO):
#	make -C ./src

#
# defines installrelease, installbeta, depend, clean
#
include ./liquidmayaRules.mk
