SHELL			= sh
PLUGSUF			= so
OBJEXT			= o
CPP				= g++
LD				= $(MAYA_LOCATION)/bin/mayald
LOCFLAGS    	= -ffast-math -mpentiumpro -D_BOOL -DLINUX
WARNFLAGS   	= -Wall -W -Wno-comment -Wpointer-arith -Wno-inline -Woverloaded-virtual -Wno-sign-compare -Wno-parentheses
# Theese warn flags are ignored by gcc 2.96 -Wtraditional -Wundef
NO_TRANS_LINK	=
VBIN			= redhat
EXTRA_LIBS		=
AR				= ar cqs

include commonrules.mk
