#!/usr/bin/perl

use strict;

my $DestDir			= $ARGV[1];

my $homeDir			= $ENV{"HOME"} || "";
my $MayaPrefsDir	= "${homeDir}/Library/Preferences/Alias/maya/7.0";
my $MayaPrefs		= "${MayaPrefsDir}/Maya.env";
my $MayaPrefsBak	= "${MayaPrefs}.bak";
my $MayaPrefsTmp	= "${MayaPrefs}.tmp";

my $EnvReplacements = {
						LIQUIDHOME	=>	"${DestDir}",
						XBMLANGPATH =>	"${DestDir}/icons",
					};

my $GlobalEnvReplacements = { };

# Work out what we were

if ( -f "${DestDir}/plugin/7.0/liquid_pixie.lib" ) {
	# Pixie
	$EnvReplacements->{PATH}		=	"\$PATH:/Applications/Graphics/Pixie/bin";
	$EnvReplacements->{PIXIEHOME}	=	"/Applications/Graphics/Pixie";
	$EnvReplacements->{DISPLAY}		=	":0.0";
	
	system("mkdir -p /Users/Shared/Alias/maya/7.0/plug-ins/ ");
	system("cp \"$DestDir/7.0/liquid_pixie.lib\" /Users/Shared/Alias/maya/7.0/plug-ins/ ");
}

if ( -f "${DestDir}/plugin/7.0/liquid_3delight.lib" ) {
	# 3Delight
	$GlobalEnvReplacements->{DYLD_LIBRARY_PATH}		=	"/Applications/Graphics/3Delight-5.0.1/lib";
	$GlobalEnvReplacements->{DELIGHT}				=	"/Applications/Graphics/3Delight-5.0.1";
	
	system("mkdir -p /Users/Shared/Alias/maya/7.0/plug-ins/ ");
	system("cp \"$DestDir/7.0/liquid_3delight.lib\" /Users/Shared/Alias/maya/7.0/plug-ins/ ");
}

# Install our stuff into Maya.env
if ( ! -d ${MayaPrefsDir} ) {
	system("mkdir -p \"${MayaPrefsDir}\" ");
}

if ( -f ${MayaPrefs} ) {
	system("cp \"${MayaPrefs}\" \"${MayaPrefsBak}\" ");
} else {
	system("touch \"${MayaPrefs}\" ");
}

open(ENVFILE,"${MayaPrefs}");
open(ENVFILEOUT,'>',"${MayaPrefsTmp}");
while(<ENVFILE>) {
	my $line = $_;
	
	foreach my $i ( keys(%$EnvReplacements) ) {
		my $pat = qr|^\s*${i}.*$|;
		if ($line =~ m|${pat}|) {
			$line = "# commented out by the liquidmaya installer \n" . "#   ".$line;
			last;
		}
	}
	print ENVFILEOUT $line;
	print $line;
}

print ENVFILEOUT "# Added by liquidmaya installer (begin)\n";
foreach my $i ( keys(%$EnvReplacements) ) {
	print ENVFILEOUT "$i = " . $EnvReplacements->{$i} . "\n";

}
print ENVFILEOUT "# Added by liquidmaya installer (end)\n\n";

close(ENVFILEOUT);
close(ENVFILE);

system(" mv \"${MayaPrefsTmp}\" \"${MayaPrefs}\" ");

# install stuff to environment plist

my @tmp = keys(%$GlobalEnvReplacements);
if ( $#tmp > -1 ) {

	if ( -f "$homeDir/.MacOSX/environment.plist" ) {
		system("cp \"$homeDir/.MacOSX/environment.plist\" \"$homeDir/.MacOSX/environment.plist.bak\" ");
	}
	
	system("mkdir -p \"$homeDir/.MacOSX/\" ");
	system("ln -s \"$homeDir/.MacOSX/environment.plist\" \"$homeDir/Library/Preferences/environment.plist\" ");
	
	foreach my $i ( keys(%$GlobalEnvReplacements) ) {
		system("defaults write environment \"$i\" \"" . $GlobalEnvReplacements->{$i} . "\" ");
	}
	
	system("rm \"$homeDir/Library/Preferences/environment.plist\" ");
}

exit 0;