SHELL 	    	= sh
PLUGSUF     	= so
OBJEXT		= o
CPP 	    	= CC
LD  	    	= $(MAYA_LOCATION)/bin/mayald
LD  	    	= CC
LOCFLAGS    	= -g -mips4 -n32 -LANG:std -D_IRIX -DUNIX -FE:template_in_elf_section
WARNFLAGS   	= 
NO_TRANS_LINK = -no_transitive_link 
VBIN=irix
EXTRA_LIBS = -lgen -lpthread
include commonrules.mk
