SHELL         = sh
PLUGSUF       = so
OBJEXT        = o
CPP           = g++334
LD            = $(MAYA_LOCATION)/bin/mayald
LOCFLAGS    	= -ffast-math -march=pentiumpro -D_BOOL -DLINUX
WARNFLAGS     = -Wall -W -Wno-comment -Wpointer-arith -Wno-inline -Woverloaded-virtual -Wno-sign-compare -Wno-parentheses -Wno-deprecated
NO_TRANS_LINK =
VBIN          = redhat
EXTRA_LIBS    =
AR            = ar cqs

include commonrules.mk
